CREATE TABLE PROPERTIES
(
ID INT NOT NULL AUTO_INCREMENT,
PROPERTY_TYPE VARCHAR(255) NOT NULL,
ADDRESS VARCHAR(255) NOT NULL,
SUBURB VARCHAR(255) NOT NULL,
NO_OF_BEDS INT NOT NULL,
PRICE INT NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT FOREIGN KEY (SUBURB) REFERENCES SUBURBS (SUBURB_NAME),
CONSTRAINT FOREIGN KEY (PROPERTY_TYPE) REFERENCES PROPERTY_TYPES (PROPERTY_TYPE)
);

/*DROP TABLE PROPERTIES;*/

INSERT INTO PROPERTIES (PROPERTY_TYPE, ADDRESS, SUBURB, NO_OF_BEDS, PRICE) VALUES ('House', '235 Turton Street', 'Sunnybank', 5, 800);
INSERT INTO PROPERTIES (PROPERTY_TYPE, ADDRESS, SUBURB, NO_OF_BEDS, PRICE) VALUES ('Apartment & Unit', '25 Allen Street', 'Sunnybank Hills', 5, 800);
