CREATE TABLE PROPERTY_TYPES
(
PROPERTY_TYPE VARCHAR(255) NOT NULL,
PRIMARY KEY (PROPERTY_TYPE)
);

INSERT INTO PROPERTY_TYPES (PROPERTY_TYPE) VALUES ('House');
INSERT INTO PROPERTY_TYPES (PROPERTY_TYPE) VALUES ('Apartment & Unit');
INSERT INTO PROPERTY_TYPES (PROPERTY_TYPE) VALUES ('Townhouse');
INSERT INTO PROPERTY_TYPES (PROPERTY_TYPE) VALUES ('Villa');
INSERT INTO PROPERTY_TYPES (PROPERTY_TYPE) VALUES ('Land');

/*DROP TABLE PROPERTY_TYPES;*/

SELECT * FROM PROPERTY_TYPES;