CREATE TABLE SUBURBS
(
POSTCODE INT NOT NULL,
SUBURB_NAME VARCHAR(255) NOT NULL,
PRIMARY KEY (SUBURB_NAME)
);

INSERT INTO SUBURBS (POSTCODE,SUBURB_NAME) VALUES (4113,'EIGHT MILE PLAINS');
INSERT INTO SUBURBS (POSTCODE,SUBURB_NAME) VALUES (4109,'SUNNYBANK HILLS');
INSERT INTO SUBURBS (POSTCODE,SUBURB_NAME) VALUES (4109,'SUNNYBANK');
INSERT INTO SUBURBS (POSTCODE,SUBURB_NAME) VALUES (4112,'KURABY');
INSERT INTO SUBURBS (POSTCODE,SUBURB_NAME) VALUES (4000,'BRISBANE CITY');
INSERT INTO SUBURBS (POSTCODE,SUBURB_NAME) VALUES (4001,'SOUTH BANK');

/*DROP TABLE SUBURBS*/;

SELECT * FROM SUBURBS;