<?php
$servername = "localhost";
$username = "user";
$password = "islam4life";

$database = "house";
if(!@mysql_connect($servername,$username,$password) || !@mysql_select_db($database)){
	die("couldn't connect");
}
mysql_query("CREATE TABLE suburbs (suburb_ID INT PRIMARY KEY IDENTITY(1,1), suburb_name VARCHAR(64))");

mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Bowen Hills')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Brisbane')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('East Brisbane')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Fortitude Valley')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Herston')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Highgate Hill')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Kangaroo Point')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Kelvin Grove')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('New Farm')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Newstead')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Paddington')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Petrie Terrace')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Red Hill')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('South Brisbane')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Spring Hill')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Teneriffe')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('West End')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Woolloongabba')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Albion')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Alderley')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Ascot')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Aspley')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Bald Hills')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Banyo')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Boondall')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Bracken Ridge')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Bridgeman Downs')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Brighton')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Brisbane Airport')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Carseldine')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Chermside')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Chermside West')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Clayfield')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Deagon')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Eagle Farm')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Everton Park')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Fitzgibbon')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Gaythorne')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Geebung')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Gordon Park')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Grange')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Hamilton')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Hendra')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Kedron')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Keperra')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Lutwyche')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('McDowall')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Mitchelton')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Myrtletown')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Newmarket')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Northgate')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Nudgee')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Nudgee Beach')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Nundah')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Pinkenba')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Sandgate')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Shorncliffe')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Stafford')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Stafford Heights')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Taigum')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Virginia')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Wavell Heights')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Wilston')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Windsor')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Wooloowin')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Zillmere')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Acacia Ridge')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Algester')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Annerley')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Archerfield')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Burbank')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Calamvale')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Carole Park')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Coopers Plains')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Darra')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Doolandella')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Drewvale')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Durack')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Dutton Park')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Eight Mile Plains')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Ellen Grove')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Fairfield')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Forest Lake')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Greenslopes')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Heathwood')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Holland Park')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Holland Park West')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Inala')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Karawatha')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Kuraby')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Larapinta')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Macgregor')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Mackenzie')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Mansfield')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Moorooka')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Mount Gravatt')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Mount Gravatt East')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Nathan')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Pallara')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Parkinson')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Richlands')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Roberston')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Rochedale')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Rocklea')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Runcorn')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Salisbury')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Seventeen Mile Rocks')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Sinnamon Park')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Stretton')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Sumner')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Sunnybank')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Sunnybank Hills')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Tarragindi')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Tennyson')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Upper Mount Gravatt')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Wacol')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Willawong')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Wishart')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Yeerongpilly')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Yeronga')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Balmoral')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Belmont')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Bulimba')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Camp Hill')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Cannon Hills')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Carina')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Carina Heights')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Carindale')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Chandler')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Coorparoo')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Gumdale')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Hawthorne')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Hemmant')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Lota')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Lytton')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Manly')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Manly West')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Moreton Island')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Morningside')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Murarrie')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Norman Park')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Port of Brisbane')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Ransome')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Seven Hills')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Tingalpa')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Wakerley')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Wynnum')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Wynnum West')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Anstead')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Ashgrove')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Auchenflower')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Bardon')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Bellbowrie')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Brookfield')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Chapel Hill')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Chelmer')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Chuwar')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Corinda')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Enoggera')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Enoggera Reservoir')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Ferny Grove')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Fig Tree Pocket')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Graceville')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Indooroopilly')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Jamboree Heights')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Jindalee')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Karana Downs')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Kenmore')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Kenmore Hills')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Kholo')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Lake Manchester')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Middle Park')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Milton')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Moggill')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Mount Coot-tha')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Mount Crosby')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Mount Ommaney')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Oxley')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Pinjarra Hills')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Pullenvale')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Riverhills')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Sherwood')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Sinnamon Park')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('St Lucia')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Taringa')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('The Gap')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Toowong')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Upper Brookfield')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Upper Kedron')");
mysql_query("INSERT INTO suburbs(suburb_name) VALUE('Westlake')");;

?>